import type { TodayNewsResponse, NewsItem, FrequencyItem, UserProfile } from "@/types/api"

// 오늘의 뉴스 목업 데이터 (세계 카테고리 제거)
export const mockTodayNews: TodayNewsResponse = {
  정치: [
    {
      news_id: "politics-1",
      category_date: "2023-05-26",
      category: "politics",
      section: "정치",
      rank: 1,
      title: "정부, 디지털 혁신 정책 발표... AI 산업 육성에 5조원 투자",
      summary:
        "정부가 디지털 혁신 정책을 발표했습니다. 이번 정책은 AI 산업 육성에 중점을 두고 있으며, 향후 5년간 5조원을 투자할 계획입니다. 전문가들은 이번 정책이 국내 AI 산업 발전에 큰 도움이 될 것으로 전망하고 있습니다.",
      image_url: "/placeholder.svg?height=400&width=600",
      thumbnail_url: "/placeholder.svg?height=200&width=300",
      content_url: "https://example.com/news/politics-1",
      publisher: "한국일보",
      author: "김정치",
      published_at: "2023-05-26T09:30:00",
      collected_at: "2023-05-26T10:00:00",
    },
    {
      news_id: "politics-2",
      category_date: "2023-05-26",
      category: "politics",
      section: "정치",
      rank: 2,
      title: "국회, 인공지능 윤리법안 통과... '책임있는 AI 개발' 강조",
      summary:
        "국회에서 인공지능 윤리법안이 통과되었습니다. 이 법안은 AI 개발 과정에서의 윤리적 책임을 강조하고 있으며, 개발자와 기업에 대한 가이드라인을 제시합니다. 법안은 내년 1월부터 시행될 예정입니다.",
      image_url: "/placeholder.svg?height=400&width=600",
      thumbnail_url: "/placeholder.svg?height=200&width=300",
      content_url: "https://example.com/news/politics-2",
      publisher: "서울신문",
      author: "이의원",
      published_at: "2023-05-26T11:15:00",
      collected_at: "2023-05-26T12:00:00",
    },
    {
      news_id: "politics-3",
      category_date: "2023-05-26",
      category: "politics",
      section: "정치",
      rank: 3,
      title: "대통령, 디지털 전환 가속화 위한 특별 위원회 설립 지시",
      summary:
        "대통령이 디지털 전환 가속화를 위한 특별 위원회 설립을 지시했습니다. 위원회는 각 부처 차관급으로 구성되며, 디지털 전환 정책의 효율적 추진을 담당하게 됩니다. 첫 회의는 다음 주에 개최될 예정입니다.",
      image_url: "/placeholder.svg?height=400&width=600",
      thumbnail_url: "/placeholder.svg?height=200&width=300",
      content_url: "https://example.com/news/politics-3",
      publisher: "중앙일보",
      author: "박대통령",
      published_at: "2023-05-26T14:00:00",
      collected_at: "2023-05-26T15:00:00",
    },
  ],
  경제: [
    {
      news_id: "economy-1",
      category_date: "2023-05-26",
      category: "economy",
      section: "경제",
      rank: 1,
      title: "글로벌 경제 불확실성 증가... 중앙은행 금리 동결 결정",
      summary:
        "글로벌 경제의 불확실성이 증가하는 가운데, 중앙은행이 기준금리를 동결하기로 결정했습니다. 이는 인플레이션 압력과 경기 침체 우려를 동시에 고려한 결정으로 분석됩니다.",
      image_url: "/placeholder.svg?height=400&width=600",
      thumbnail_url: "/placeholder.svg?height=200&width=300",
      content_url: "https://example.com/news/economy-1",
      publisher: "경제일보",
      author: "최경제",
      published_at: "2023-05-26T08:45:00",
      collected_at: "2023-05-26T09:30:00",
    },
    {
      news_id: "economy-2",
      category_date: "2023-05-26",
      category: "economy",
      section: "경제",
      rank: 2,
      title: "국내 주요 기업 2분기 실적 전망 밝아... IT 섹터 중심 성장세",
      summary:
        "국내 주요 기업들의 2분기 실적 전망이 밝아지고 있습니다. 특히 IT 섹터를 중심으로 한 성장세가 두드러지며, 반도체와 AI 관련 기업들의 실적이 크게 개선될 것으로 예상됩니다.",
      image_url: "/placeholder.svg?height=400&width=600",
      thumbnail_url: "/placeholder.svg?height=200&width=300",
      content_url: "https://example.com/news/economy-2",
      publisher: "비즈니스투데이",
      author: "김분기",
      published_at: "2023-05-26T10:30:00",
      collected_at: "2023-05-26T11:15:00",
    },
    {
      news_id: "economy-3",
      category_date: "2023-05-26",
      category: "economy",
      section: "경제",
      rank: 3,
      title: "신재생 에너지 투자 급증... ESG 경영 확산 영향",
      summary:
        "신재생 에너지 분야에 대한 투자가 급증하고 있습니다. 이는 기업들의 ESG 경영 확산에 따른 것으로, 특히 태양광과 풍력 발전 분야에 대한 투자가 크게 늘어났습니다.",
      image_url: "/placeholder.svg?height=400&width=600",
      thumbnail_url: "/placeholder.svg?height=200&width=300",
      content_url: "https://example.com/news/economy-3",
      publisher: "에너지경제",
      author: "이그린",
      published_at: "2023-05-26T13:20:00",
      collected_at: "2023-05-26T14:00:00",
    },
  ],
  "IT/과학": [
    {
      news_id: "tech-1",
      category_date: "2023-05-26",
      category: "tech",
      section: "IT/과학",
      rank: 1,
      title: "새로운 AI 기술 개발... 자연어 처리 능력 인간 수준 도달",
      summary:
        "최근 개발된 AI 기술이 자연어 처리 능력에서 인간 수준에 도달했다는 연구 결과가 발표되었습니다. 이 기술은 다양한 산업 분야에 적용될 것으로 기대됩니다.",
      image_url: "/placeholder.svg?height=400&width=600",
      thumbnail_url: "/placeholder.svg?height=200&width=300",
      content_url: "https://example.com/news/tech-1",
      publisher: "테크뉴스",
      author: "박인공",
      published_at: "2023-05-26T09:00:00",
      collected_at: "2023-05-26T09:45:00",
    },
    {
      news_id: "tech-2",
      category_date: "2023-05-26",
      category: "tech",
      section: "IT/과학",
      rank: 2,
      title: "양자 컴퓨팅 상용화 앞당겨져... 국내 기업 기술 개발 박차",
      summary:
        "양자 컴퓨팅 기술의 상용화가 예상보다 빨라질 것으로 전망됩니다. 국내 주요 기업들도 양자 컴퓨팅 기술 개발에 박차를 가하고 있으며, 정부 차원의 지원도 확대될 예정입니다.",
      image_url: "/placeholder.svg?height=400&width=600",
      thumbnail_url: "/placeholder.svg?height=200&width=300",
      content_url: "https://example.com/news/tech-2",
      publisher: "사이언스타임즈",
      author: "김양자",
      published_at: "2023-05-26T11:30:00",
      collected_at: "2023-05-26T12:15:00",
    },
    {
      news_id: "tech-3",
      category_date: "2023-05-26",
      category: "tech",
      section: "IT/과학",
      rank: 3,
      title: "우주 탐사 새 시대... 민간 기업 주도 달 탐사 프로젝트 성공",
      summary:
        "민간 기업이 주도한 달 탐사 프로젝트가 성공적으로 진행되었습니다. 이는 우주 탐사의 새로운 시대를 여는 중요한 이정표로 평가받고 있으며, 향후 화성 탐사에도 민간 참여가 확대될 전망입니다.",
      image_url: "/placeholder.svg?height=400&width=600",
      thumbnail_url: "/placeholder.svg?height=200&width=300",
      content_url: "https://example.com/news/tech-3",
      publisher: "스페이스저널",
      author: "이우주",
      published_at: "2023-05-26T14:45:00",
      collected_at: "2023-05-26T15:30:00",
    },
  ],
  사회: [
    {
      news_id: "society-1",
      category_date: "2023-05-26",
      category: "society",
      section: "사회",
      rank: 1,
      title: "교육부, 디지털 리터러시 교육 강화 방안 발표",
      summary:
        "교육부가 디지털 리터러시 교육 강화 방안을 발표했습니다. 초중고 교육과정에 디지털 윤리와 정보 판별 능력 향상을 위한 내용이 추가되며, 교사 연수도 확대될 예정입니다.",
      image_url: "/placeholder.svg?height=400&width=600",
      thumbnail_url: "/placeholder.svg?height=200&width=300",
      content_url: "https://example.com/news/society-1",
      publisher: "교육신문",
      author: "정교육",
      published_at: "2023-05-26T08:30:00",
      collected_at: "2023-05-26T09:15:00",
    },
    {
      news_id: "society-2",
      category_date: "2023-05-26",
      category: "society",
      section: "사회",
      rank: 2,
      title: "환경부, 탄소중립 실현 위한 시민 참여 프로그램 확대",
      summary:
        "환경부가 탄소중립 실현을 위한 시민 참여 프로그램을 확대한다고 발표했습니다. 지역별 탄소중립 실천단이 구성되며, 가정과 학교에서의 실천 방안도 제시될 예정입니다.",
      image_url: "/placeholder.svg?height=400&width=600",
      thumbnail_url: "/placeholder.svg?height=200&width=300",
      content_url: "https://example.com/news/society-2",
      publisher: "환경일보",
      author: "김환경",
      published_at: "2023-05-26T10:45:00",
      collected_at: "2023-05-26T11:30:00",
    },
  ],
  "생활/문화": [
    {
      news_id: "culture-1",
      category_date: "2023-05-26",
      category: "culture",
      section: "생활/문화",
      rank: 1,
      title: "국립중앙박물관, AI 기술 활용한 새로운 전시 방식 도입",
      summary:
        "국립중앙박물관이 AI 기술을 활용한 새로운 전시 방식을 도입했습니다. 관람객은 증강현실(AR)을 통해 유물의 원래 모습과 사용 방법을 체험할 수 있으며, AI 큐레이터의 안내도 받을 수 있습니다.",
      image_url: "/placeholder.svg?height=400&width=600",
      thumbnail_url: "/placeholder.svg?height=200&width=300",
      content_url: "https://example.com/news/culture-1",
      publisher: "문화저널",
      author: "이문화",
      published_at: "2023-05-26T09:15:00",
      collected_at: "2023-05-26T10:00:00",
    },
    {
      news_id: "culture-2",
      category_date: "2023-05-26",
      category: "culture",
      section: "생활/문화",
      rank: 2,
      title: "디지털 노마드 라이프스타일 확산... 지방 소도시 활성화에 기여",
      summary:
        "디지털 노마드 라이프스타일이 확산되면서 지방 소도시가 활성화되고 있습니다. 원격 근무가 가능한 직장인들이 자연 환경이 좋은 지방으로 이주하는 추세가 뚜렷해지고 있습니다.",
      image_url: "/placeholder.svg?height=400&width=600",
      thumbnail_url: "/placeholder.svg?height=200&width=300",
      content_url: "https://example.com/news/culture-2",
      publisher: "라이프매거진",
      author: "박라이프",
      published_at: "2023-05-26T12:00:00",
      collected_at: "2023-05-26T12:45:00",
    },
  ],
  연예: [
    {
      news_id: "entertainment-1",
      category_date: "2023-05-26",
      category: "entertainment",
      section: "연예",
      rank: 1,
      title: "K-POP 그룹, 글로벌 차트 1위... 한류 열풍 지속",
      summary:
        "국내 K-POP 그룹이 글로벌 음악 차트에서 1위를 차지했습니다. 이는 한류 열풍이 지속되고 있음을 보여주는 사례로, 국내 음악 산업의 글로벌 경쟁력을 입증했습니다.",
      image_url: "/placeholder.svg?height=400&width=600",
      thumbnail_url: "/placeholder.svg?height=200&width=300",
      content_url: "https://example.com/news/entertainment-1",
      publisher: "엔터테인먼트투데이",
      author: "김한류",
      published_at: "2023-05-26T16:00:00",
      collected_at: "2023-05-26T16:30:00",
    },
  ],
  스포츠: [
    {
      news_id: "sports-1",
      category_date: "2023-05-26",
      category: "sports",
      section: "스포츠",
      rank: 1,
      title: "국내 프로스포츠, 디지털 팬 경험 강화 위한 기술 도입 확대",
      summary:
        "국내 프로스포츠 구단들이 디지털 팬 경험 강화를 위한 기술 도입을 확대하고 있습니다. AR/VR을 활용한 실감형 중계, 선수 데이터 분석 서비스 등 다양한 기술이 적용되고 있습니다.",
      image_url: "/placeholder.svg?height=400&width=600",
      thumbnail_url: "/placeholder.svg?height=200&width=300",
      content_url: "https://example.com/news/sports-1",
      publisher: "스포츠타임즈",
      author: "최스포츠",
      published_at: "2023-05-26T15:30:00",
      collected_at: "2023-05-26T16:15:00",
    },
  ],
}

// 랭킹 뉴스 목업 데이터 (세계 카테고리 제거)
export const mockRankingNews: NewsItem[] = [
  {
    news_id: "ranking-1",
    category_date: "2023-05-26",
    category: "economy",
    section: "경제",
    rank: 1,
    title: "중앙은행, 기준금리 동결 결정... 경기 회복세 지켜본다",
    summary:
      "중앙은행이 이번 달 기준금리를 동결하기로 결정했습니다. 이는 최근의 경기 회복세를 지켜보며 신중한 접근을 취하겠다는 의미로 해석됩니다. 전문가들은 하반기 경제 지표에 따라 금리 인상 가능성도 있다고 전망합니다.",
    image_url: "/placeholder.svg?height=400&width=600",
    thumbnail_url: "/placeholder.svg?height=200&width=300",
    content_url: "https://example.com/news/ranking-1",
    publisher: "경제신문",
    author: "김금리",
    published_at: "2023-05-26T08:00:00",
    collected_at: "2023-05-26T08:30:00",
  },
  {
    news_id: "ranking-2",
    category_date: "2023-05-26",
    category: "tech",
    section: "IT/과학",
    rank: 2,
    title: "국내 IT 기업, 생성형 AI 기술 개발에 1조원 투자 계획 발표",
    summary:
      "국내 주요 IT 기업이 생성형 AI 기술 개발에 향후 3년간 1조원을 투자하겠다는 계획을 발표했습니다. 이를 통해 글로벌 AI 시장에서의 경쟁력을 강화하고 관련 일자리 5천개를 창출할 것으로 기대됩니다.",
    image_url: "/placeholder.svg?height=400&width=600",
    thumbnail_url: "/placeholder.svg?height=200&width=300",
    content_url: "https://example.com/news/ranking-2",
    publisher: "테크타임스",
    author: "이기술",
    published_at: "2023-05-26T09:15:00",
    collected_at: "2023-05-26T10:00:00",
  },
  {
    news_id: "ranking-3",
    category_date: "2023-05-26",
    category: "politics",
    section: "정치",
    rank: 3,
    title: "정부, 디지털 전환 가속화 위한 규제 완화 방안 발표",
    summary:
      "정부가 디지털 전환 가속화를 위한 규제 완화 방안을 발표했습니다. 이번 방안은 신기술 도입과 디지털 혁신을 저해하는 규제를 개선하는 내용을 담고 있으며, 산업계의 호응을 얻고 있습니다.",
    image_url: "/placeholder.svg?height=400&width=600",
    thumbnail_url: "/placeholder.svg?height=200&width=300",
    content_url: "https://example.com/news/ranking-3",
    publisher: "정책저널",
    author: "박정책",
    published_at: "2023-05-26T10:30:00",
    collected_at: "2023-05-26T11:15:00",
  },
  {
    news_id: "ranking-4",
    category_date: "2023-05-26",
    category: "society",
    section: "사회",
    rank: 4,
    title: "교육계, AI 활용 교육 확대... '디지털 네이티브' 세대 맞춤형 학습",
    summary:
      "교육계가 AI를 활용한 교육을 확대하고 있습니다. 이는 '디지털 네이티브' 세대에 맞춤형 학습 경험을 제공하기 위한 것으로, 개인별 학습 진도와 성취도에 따른 맞춤형 콘텐츠 제공이 가능해집니다.",
    image_url: "/placeholder.svg?height=400&width=600",
    thumbnail_url: "/placeholder.svg?height=200&width=300",
    content_url: "https://example.com/news/ranking-4",
    publisher: "교육저널",
    author: "최교육",
    published_at: "2023-05-26T11:45:00",
    collected_at: "2023-05-26T12:30:00",
  },
  {
    news_id: "ranking-5",
    category_date: "2023-05-26",
    category: "culture",
    section: "생활/문화",
    rank: 5,
    title: "MZ세대, '디지털 디톡스' 트렌드 확산... 아날로그 취미 인기",
    summary:
      "MZ세대 사이에서 '디지털 디톡스' 트렌드가 확산되고 있습니다. 디지털 기기 사용을 줄이고 아날로그 취미를 즐기는 이들이 늘어나면서, 필름 카메라, 비닐 레코드, 종이책 등의 판매량이 증가하고 있습니다.",
    image_url: "/placeholder.svg?height=400&width=600",
    thumbnail_url: "/placeholder.svg?height=200&width=300",
    content_url: "https://example.com/news/ranking-5",
    publisher: "트렌드투데이",
    author: "정트렌드",
    published_at: "2023-05-26T13:00:00",
    collected_at: "2023-05-26T13:45:00",
  },
]

// 내 주파수 목업 데이터 (실제 DynamoDB 구조에 맞게 수정)
export const mockFrequencies: FrequencyItem[] = [
  {
    frequency_id: "politics#2025-06-02",
    category: "politics",
    date: "2025-06-02",
    script:
      "안녕하세요, 여러분. 지적이고 친절한 팟캐스트 진행자입니다. 오늘은 정치 분야의 주요 이슈들을 함께 살펴보려 합니다. 정부가 디지털 혁신 정책을 발표했습니다. 이번 정책은 AI 산업 육성에 중점을 두고 있으며, 향후 5년간 5조원을 투자할 계획입니다. 국회에서는 인공지능 윤리법안이 통과되었습니다. 이 법안은 AI 개발 과정에서의 윤리적 책임을 강조하고 있으며, 개발자와 기업에 대한 가이드라인을 제시합니다. 대통령은 디지털 전환 가속화를 위한 특별 위원회 설립을 지시했습니다. 위원회는 각 부처 차관급으로 구성되며, 디지털 전환 정책의 효율적 추진을 담당하게 됩니다.",
    audio_url: "https://briefly-news-audio.s3.amazonaws.com/news-audio/2025-06-02/shared/politics.mp3",
    created_at: "2025-06-02T06:00:00.000000",
    duration: 180,
  },
  {
    frequency_id: "economy#2025-06-02",
    category: "economy",
    date: "2025-06-02",
    script:
      "안녕하세요, 여러분. 지적이고 친절한 팟캐스트 진행자입니다. 오늘은 경제 분야의 주요 이슈들을 함께 살펴보려 합니다. 글로벌 경제의 불확실성이 증가하는 가운데, 중앙은행이 기준금리를 동결하기로 결정했습니다. 이는 인플레이션 압력과 경기 침체 우려를 동시에 고려한 결정으로 분석됩니다. 국내 주요 기업들의 2분기 실적 전망이 밝아지고 있습니다. 특히 IT 섹터를 중심으로 한 성장세가 두드러지며, 반도체와 AI 관련 기업들의 실적이 크게 개선될 것으로 예상됩니다. 신재생 에너지 분야에 대한 투자가 급증하고 있습니다.",
    audio_url: "https://briefly-news-audio.s3.amazonaws.com/news-audio/2025-06-02/shared/economy.mp3",
    created_at: "2025-06-02T06:00:00.000000",
    duration: 165,
  },
  {
    frequency_id: "tech#2025-06-02",
    category: "tech",
    date: "2025-06-02",
    script:
      "안녕하세요, 여러분. 지적이고 친절한 팟캐스트 진행자입니다. 오늘은 IT/과학 분야의 주요 이슈들을 함께 살펴보려 합니다. 최근 개발된 AI 기술이 자연어 처리 능력에서 인간 수준에 도달했다는 연구 결과가 발표되었습니다. 이 기술은 다양한 산업 분야에 적용될 것으로 기대됩니다. 양자 컴퓨팅 기술의 상용화가 예상보다 빨라질 것으로 전망됩니다. 국내 주요 기업들도 양자 컴퓨팅 기술 개발에 박차를 가하고 있으며, 정부 차원의 지원도 확대될 예정입니다. 민간 기업이 주도한 달 탐사 프로젝트가 성공적으로 진행되었습니다.",
    audio_url: "https://briefly-news-audio.s3.amazonaws.com/news-audio/2025-06-02/shared/tech.mp3",
    created_at: "2025-06-02T06:00:00.000000",
    duration: 175,
  },
  {
    frequency_id: "society#2025-06-02",
    category: "society",
    date: "2025-06-02",
    script:
      "안녕하세요, 여러분. 지적이고 친절한 팟캐스트 진행자입니다. 오늘은 사회 분야의 주요 이슈들을 함께 살펴보려 합니다. 최근 다양한 사건과 소식들이 우리 사회를 떠들썩하게 하고 있는데요, 함께 그 내용을 알아보겠습니다. 교육계가 AI를 활용한 교육을 확대하고 있습니다. 이는 '디지털 네이티브' 세대에 맞춤형 학습 경험을 제공하기 위한 것으로, 개인별 학습 진도와 성취도에 따른 맞춤형 콘텐츠 제공이 가능해집니다. MZ세대 사이에서 '디지털 디톡스' 트렌드가 확산되고 있습니다.",
    audio_url: "https://briefly-news-audio.s3.amazonaws.com/news-audio/2025-06-02/shared/society.mp3",
    created_at: "2025-06-02T15:03:05.173195",
    duration: 160,
  },
  {
    frequency_id: "politics#2025-06-01",
    category: "politics",
    date: "2025-06-01",
    script:
      "안녕하세요, 여러분. 지적이고 친절한 팟캐스트 진행자입니다. 어제의 정치 분야 주요 소식을 전해드립니다. 국회에서 디지털 정부 혁신법이 통과되었습니다. 이 법안은 공공 서비스의 디지털화를 가속화하고, 시민들의 접근성을 높이는 내용을 담고 있습니다. 여야는 디지털 경제 활성화를 위한 초당적 협력을 약속했습니다. 특히 스타트업 지원과 디지털 인프라 구축에 중점을 둘 예정입니다. 정부는 사이버 보안 강화 대책을 발표했습니다.",
    audio_url: "https://briefly-news-audio.s3.amazonaws.com/news-audio/2025-06-01/shared/politics.mp3",
    created_at: "2025-06-01T06:00:00.000000",
    duration: 155,
  },
  {
    frequency_id: "economy#2025-06-01",
    category: "economy",
    date: "2025-06-01",
    script:
      "안녕하세요, 여러분. 지적이고 친절한 팟캐스트 진행자입니다. 어제의 경제 분야 주요 소식을 전해드립니다. 국내 주식 시장이 기술주 중심으로 상승세를 보였습니다. 특히 AI와 반도체 관련 종목들의 강세가 두드러졌습니다. 정부가 디지털 뉴딜 2.0 정책을 발표했습니다. 이번 정책은 디지털 전환 가속화와 함께 포용적 성장을 강조하고 있습니다. 주요 경제 연구소들이 올해 경제 성장률 전망치를 상향 조정했습니다.",
    audio_url: "https://briefly-news-audio.s3.amazonaws.com/news-audio/2025-06-01/shared/economy.mp3",
    created_at: "2025-06-01T06:00:00.000000",
    duration: 145,
  },
]

// 사용자 프로필 목업 데이터
export const mockUserProfile: UserProfile = {
  user_id: "user123",
  nickname: "디지털러버",
  profile_image: "/placeholder.svg?height=100&width=100",
  created_at: "2023-01-15T10:30:00",
  interests: ["politics", "economy", "tech"],
  onboarding_completed: true,
  default_length: 3,
}

// 사용자 카테고리 목업 데이터 (세계 제거)
export const mockUserCategories = ["politics", "economy", "tech"]

// 북마크 상태 목업 데이터
export const mockBookmarks = ["tech-1", "economy-2", "ranking-3"]

// 카테고리 목업 데이터 (세계 제거)
export const mockCategories = ["politics", "economy", "society", "culture", "tech", "entertainment", "sports"]
